Repository AY2324S1-CS2103T-T14-3/tp, pull requests merged in 2023-11, with the labels that each got.

#130 Update FAQ section in User Guide
  docs/UserGuide.md
Labels: type.Task

#135 Fix bug where delete, edit not affecting original list after find
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AppendLogCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearLogCommandTest.java
  src/test/java/seedu/address/logic/commands/LogCommandTest.java
Labels: type.Bug

#132 Add logic to show reminders on startup
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AppendLogCommand.java
  src/main/java/seedu/address/logic/commands/LogCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/predicates/AppointmentOverlapsPredicate.java
  src/test/java/seedu/address/logic/commands/AppendLogCommandTest.java
  src/test/java/seedu/address/logic/commands/LogCommandTest.java
Labels: priority.Low, type.Enhancement

#200 Add spacing in Data File in UG FAQ
  docs/UserGuide.md
Labels: type.Bug

#202 GUI branch
  docs/UserGuide.md
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug

#204 Update repo to resolve issues and bugs.
  docs/UserGuide.md
  docs/images/Ui_v1.3.1.jpg
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Id.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
Labels: type.Bug, severity.High

#213 Update own PPP for deliverable this week (WH)
  docs/images/HealthSyncGUI_v1.4.png
  docs/images/SceneBuilder.png
  docs/team/weeehung.md
Labels: type.Task

#203 Explain the concept of log
  docs/UserGuide.md
  docs/images/originalLog.jpg
Labels: type.Bug, severity.Low

#209 Update UG to account for Git Issues
  README.md
  docs/UserGuide.md
  docs/images/quickstartGUI.PNG
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Bug

#212 Update own PPP for deliverable this week
  docs/team/wzwren.md
Labels: type.Task

#220 Fix UI bug resulting from ID refactor
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug

#216 Include some Logging and Update Test Cases for Model
  src/main/java/seedu/address/model/person/MedicalHistory.java
  src/main/java/seedu/address/ui/LoggedPersonListPanel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/IdTest.java
  src/test/java/seedu/address/model/person/MedicalHistoryTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: priority.Medium, type.Enhancement

#211 Fix PED Bugs in UG for Add Command and Glossary
  docs/UserGuide.md
Labels: type.Bug

#244 Revert Changes on Medical History Validation
  src/main/java/seedu/address/model/person/MedicalHistory.java
  src/test/java/seedu/address/model/person/MedicalHistoryTest.java
Labels: type.Bug

#228 Update all SS for v1.4 in UG
  docs/UserGuide.md
  docs/images/UI_v1.2.1.jpg
  docs/images/UI_v1.3.jpg
  docs/images/Ui.png
  docs/images/Ui_v1.3.1.jpg
  docs/images/addResult.jpg
  docs/images/address_book_32.jpg
  docs/images/alogResult.jpg
  docs/images/clearResult.jpg
  docs/images/clogResult.jpg
  docs/images/deleteResult.jpg
  docs/images/editResult.jpg
  docs/images/findidT0123456FResult.jpg
  docs/images/listResult.jpg
  docs/images/logResult.jpg
  docs/images/originalLog.jpg
  docs/images/quickstartGUI.PNG
  docs/images/undoResult.jpg
  docs/images/v1.4-screenshots/add.jpg
  docs/images/v1.4-screenshots/alog.jpg
  docs/images/v1.4-screenshots/clear.jpg
  docs/images/v1.4-screenshots/clog.jpg
  docs/images/v1.4-screenshots/delete.jpg
  docs/images/v1.4-screenshots/edit.jpg
  docs/images/v1.4-screenshots/find.jpg
  docs/images/v1.4-screenshots/list.jpg
  docs/images/v1.4-screenshots/log.jpg
  docs/images/v1.4-screenshots/logExample.jpg
  docs/images/v1.4-screenshots/personCard.jpg
  docs/images/v1.4-screenshots/quickstartGUI.jpg
  docs/images/v1.4-screenshots/undo.jpg
Labels: priority.Medium, type.Enhancement

#246 Update landing page for website
  docs/index.md
Labels: priority.Medium, type.Enhancement

#250 Update NFR in DG
  docs/DeveloperGuide.md
Labels: type.Task

#249 Update existing DG use cases
  docs/DeveloperGuide.md
Labels: type.Task

#247 Dereference `delete 1` in Architecture section
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
Labels: type.Task

#245 Update Diagrams under Logic section to include UndoableCommand
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
Labels: type.Task

#248 Fix diagrams in Optional, Appointment sections
  docs/DeveloperGuide.md
  docs/diagrams/AppointmentActivity0.puml
  docs/diagrams/AppointmentSequence0.puml
Labels: type.Bug

#252 Update DG as per assignments
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: type.Task

#269 Update App Version v1.4.1
  src/main/java/seedu/address/MainApp.java
Labels: type.Task
