Repository AY2324S1-CS2103T-T14-3/tp, pull requests merged in 2023-10, with the labels that each got.

#43 Update Non-Functional Requirements (NFRs) for DG
  docs/DeveloperGuide.md
Labels: help wanted

#63 Add New Fields for Person Class
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/MedicalHistory.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedMedicalHistory.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/person/AppointmentTest.java
  src/test/java/seedu/address/model/person/MedicalHistoryTest.java
  src/test/java/seedu/address/model/person/NricTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMedicalHistoryTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#75 Updated delete
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#80 Update UI image in UG and change display name of app
  docs/images/Ui.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium

#87 Update the message usage of Delete Command
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: type.Enhancement

#85 Allow editing of multiple medical histories and remove tags from Ui
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/MedicalHistory.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Medium

#91 Add Log command to UG
  docs/UserGuide.md
Labels: type.Task

#93 Add draft of DG enhancements for Appointments, Interface
  docs/DeveloperGuide.md
Labels: type.Task

#110 Change Appointment to use Date instead of String
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/enums/InputSource.java
  src/main/java/seedu/address/model/person/exceptions/BadAppointmentFormatException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#111 Add Alias for all existing commands.
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.Medium
